### ISSUE TITLE
Botania flowers don't work when using CleanroomMC

### ISSUE THREAD

**Issue by nimuck** [Elephant1214/PaperFixes#6]
This is just a reupload of [the one I posted on the Fugue issue tab](https://github.com/CleanroomMC/Fugue/issues/50).

I've only tested on [prismlauncher](https://prismlauncher.org/) with [pre-made instance](https://github.com/CleanroomMC/Cleanroom/releases/download/0.2.2-alpha/Cleanroom-MMC-instance-0.2.2-alpha.zip), but of course you may replicate this no matter which launcher you choose.

in case you've never heard of cleanroom:
- [CleanroomMC](https://github.com/CleanroomMC/Cleanroom) is a modloader in active development and it utilizes latest java(> 21) and LWJGL3. (which are known to provide much better performance than older versions)
- [Fugue](https://github.com/CleanroomMC/Fugue) is a mod patches cleanroom's incompats.

**Comment by Elephant1214** [comment]
I don't know why he's saying I'm blindly applying patches from Paper, I'm not and the only slight example of this is a lighting fix that didn't have a lower priority to allow lighting engines to overwrite it. Heck, a Cleanroom dev actually wanted me to merge this with Universal Tweaks. First off, did you restart after changing the config options? They disable Mixins, so they can't be changed on the fly.

**Comment by nimuck** [comment]
Yes of course I restarted it, and even tested it after changing all options to false one-by-one in notepad, worrying the case that if I modified it in-game config would not be applied
(cuz I've seen a few mods make that mistake)

Anyway cleanroom itself currently does not provide a config option to turn its 'fixes' on or off,
instead they left all compatibility issues to fugue
So if you can afford it, I recommend meeting with the fugue developer - since he seems to think paperfixes are too big to find incompats on his own, and vice versa.

**Comment by Elephant1214** [comment]
Could you friend me on Discord so we can talk about this more? `elephant_1214`

**Comment by Elephant1214** [comment]
Fixed in 1.2.0
