### ISSUE TITLE
[Bug] MC-54738 persists

### ISSUE THREAD

**Issue by ShinyArmorYT** [Elephant1214/PaperFixes#8]
[MC-54738](https://bugs.mojang.com/browse/MC-54738) can still be replicated using the steps on its issue report with only the latest versions of [PaperFixes](https://www.curseforge.com/minecraft/mc-mods/paperfixes) (1.3.0) and [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) (9.4) loaded:

![image](https://github.com/user-attachments/assets/82cc8926-de23-476e-a781-98f3dd90241a)

**Comment by Elephant1214** [comment]
Fixed in [b4700605555062dee4500079488063a3bde19c3f](https://github.com/Elephant1214/PaperFixes/commit/b4700605555062dee4500079488063a3bde19c3f)
